ip = '10.230.189.148'
port = 1521
SID = 'balci'
dbPassword = 'nanderson'
dbUserName = 'aohagan'

transferClassList=[
'APLSUPBAL',
'ZCFISD01',
'UKEMBTRTRCC',
'UKRMOBILECOLO',
'APLSUP78',
'UKEPROFILE',
'UKEBILLINGDI',
'UKEAVALONRES',
'CWSAIMSA', 
'UKRBROADBANDCOLO', 
'UKRVASCOLO', 
'UKESAAS3LS', 
'APLSUPROBTESB', 
'ESBROBTXMLGWSUP', 
'APLSUPPMFCPEDB', 
'APLSUPPMFWS', 
'APLSUPPMF', 
'UKEPDTNGPDB',
]

cepQueuesApplications = ["OFS", "MCSO", "BT.COM OSCH PLATFORM", "BALA", "WLR3 FLOWMANAGE OPENREACH", "PMF ARGON", "CS-APPLICATION", "OR PMF", "UKB AGENT DESKTOP", "SIEBEL ONEVIEW", "BT RETAIL EOI B2B GATEWAY", "BT SPORT DIGITAL DEVICE APPS",
						 "ACTIVEMEDIATION", "DIRECTORY AND PROFILE", "KCI", "ASC", "OPENREACH B2B GATEWAY", "PSG FLOW OR", "AMDOCS", "RETAIL RECEIPTS", "BAL A", "CSS", "GENIUS", "PMF ORACLE", "AVALON BAL B ", "PSG FLOW BTR", "ACCESS", "EE HOME POS"]
cepIncidents2016Applications = ["AVALON RES", "OFS", "KCIM", "EIM", "ONM", "BT BUYNET", "BALA", "THISTLE", "VAS FULFILMENT", "ACTIVEMEDIATION", "HERCULES", "DIRECTORY AND PROFILE",
								"BAL A_REV", "GIBO", "BALB AVALON1 ", "AMDOCS", "GENERAL GIB PLATFORM", "RBSC", "RETAIL RECEIPTS", "HECTOR RETAIL", "BACSTEL-IP", "BAL A", "BTINTERNET WEB PAGES", "BT MYDONATE", "ESB ROBT", "ESB ROBT I&G"]